### ISSUE TITLE
Error opening settings in v10

### ISSUE THREAD

**Issue by strongpauly** [League-of-Foundry-Developers/fvtt-module-theatre#105]
A console error is shown when trying to open the settings dialog with this module enabled in v10 Release 10.284

```
foundry.js:711 Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:3630:15)
    at SchemaField.validate (commons.js:3357:37)
    at Setting.validate (commons.js:4994:35)
    at new DataModel (commons.js:4771:26)
    at new Document (commons.js:5310:3)
    at new BaseSetting (commons.js:9319:3)
    at new ClientDocumentMixin (foundry.js:12942:5)
    at new Setting (foundry.js:21144:1)
    at ClientSettings.get (foundry.js:2723:21)
    at SettingsConfig._prepareCategoryData (foundry.js:70821:31)
    at SettingsConfig.getData (foundry.js:58949:23)
    at SettingsConfig._render (foundry.js:4959:29)
    at SettingsConfig._render (foundry.js:5684:17)
    at SettingsConfig._render (foundry.js:59018:18)
```

**Comment by megahead11** [comment]
Theatre is not officially compatible with V10 _yet_. We're working on getting a fix for v10 at the moment. Thanks though, we'll look into this ^^

**Comment by megahead11** [comment]
Fixed in the latest release ^^

**Comment by Kryomancer** [comment]
I'm getting this same error currently on 2.2.2:

```
Error: An error occurred while rendering SettingsConfig 62. Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Setting.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseSetting (commons.js:9832:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Setting (foundry.js:21323:1)
    at ClientSettings.get (foundry.js:2815:21)
    at SettingsConfig._prepareCategoryData (foundry.js:71959:31)
    at SettingsConfig.getData (foundry.js:59910:23)
    at SettingsConfig._render (foundry.js:5108:29)
    at SettingsConfig._render (foundry.js:5822:17)
    at SettingsConfig._render (foundry.js:59979:18)
```

I'm unable to try out 2.5.1 as the system I'm using only works up to Foundry version 10. Seems like this problem may have regressed?
