### ISSUE TITLE
#105 Regression: Error opening settings in v10

### ISSUE THREAD

**Issue by Kryomancer** [League-of-Foundry-Developers/fvtt-module-theatre#136]
It seems https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/issues/105 has regressed. I'm on Foundry v10, build 303 (unable to update to 11 as the system I'm using has not yet been updated), Theatre inserts module is 2.2.2, the last one to support v10, and when hitting Configure Settings I get the same kind of error:

```
Error: An error occurred while rendering SettingsConfig 62. Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Setting.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseSetting (commons.js:9832:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Setting (foundry.js:21323:1)
    at ClientSettings.get (foundry.js:2815:21)
    at SettingsConfig._prepareCategoryData (foundry.js:71959:31)
    at SettingsConfig.getData (foundry.js:59910:23)
    at SettingsConfig._render (foundry.js:5108:29)
    at SettingsConfig._render (foundry.js:5822:17)
    at SettingsConfig._render (foundry.js:59979:18)
```

Additionally, while I can add actors to the stage, all of the chat messages get sent as normal GM messages and the players see none of this module's UI.

**Comment by Kryomancer** [comment]
It appears you have to manually install 2.4.0 from the releases as it's not published on the Foundry module repository to fix this. It would be nice to have it in there as the one that gets installed if you're on v10 instead of the nonfunctional 2.2.2, though.

**Comment by KingPivot** [comment]
Could you tell me how this was done? This is the only reported issue that is exactly the same as i am currently experiencing.

**Comment by friendtocephalopods** [comment]
Thanks for the fix! I had this same problem when I grabbed the module.json from the `v10` branch. Installing the v2.4.0 release manifest in foundry solved it for me too. @KingPivot , that's at: `https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/releases/download/v2.4.0/module.json`.

**Comment by Joswea** [comment]
This was perfect- fixed my issue right away. Make sure you're using the 2.4 release that friendtocephalopods linked aboved
