### ISSUE TITLE
[BUG] Incompatible with Sequencer

### ISSUE THREAD

**Issue by MrFlaig** [League-of-Foundry-Developers/fvtt-module-theatre#173]
Foundry: v12.331
D&D: 3.3.1
Sequencer 3.2.16
Theatre Inserts: 2.9.1

**Error description:**

The Chatbar Integration does not render and the module throws only errormessages if using a macro.

**Error on load:**

foundry.js:655 Error: Error thrown in hooked function '' for hook 'renderChatLog'. Cannot read properties of null (reading 'generateShader')
[Detected 1 package: theatre(v2.9.1)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at ChatLog._callHooks (foundry.js:5918:13)
    at ChatLog._render (foundry.js:5879:10)
    at async ChatLog._render (foundry.js:72780:5)
    at async ChatLog._render (foundry.js:89330:5)
    at async Promise.all (index 2)

**Error on Macro use:**

Uncaught (in promise) ReferenceError: undefined. Theatre is not defined
[No packages detected]
    at Macro.eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:4:5)
    at #executeScript (foundry.js:20087:17)
    at Macro.execute (foundry.js:20028:35)
    at Hotbar._onClickMacro (foundry.js:82722:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by MrFlaig** [comment]
Sorry i forgot to activate the debugging so here are the errormessages with debugging activated:

Error: Error thrown in hooked function '' for hook 'renderChatLog'. Cannot read properties of null (reading 'generateShader')
[Detected 1 package: theatre(v2.9.1)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at ChatLog._callHooks (foundry.js:5918:13)
    at ChatLog._render (foundry.js:5879:10)
    at async ChatLog._render (foundry.js:72780:5)
    at async ChatLog._render (foundry.js:89330:5)
    at async Promise.all (index 2)Caused by: TypeError: Error thrown in hooked function '' for hook 'renderChatLog'. Cannot read properties of null (reading 'generateShader')
[Detected 1 package: theatre(v2.9.1)]
    at BatchPlugin.onPrerender (foundry.js:42716:43)
    at o.emit (index.js:201:33)
    at xn.render (ObjectRendererSystem.ts:70:18)
    at ea.render (Renderer.ts:377:29)
    at na.render (Application.ts:90:23)
    at mn.emit (TickerListener.ts:67:25)
    at Pt.update (Ticker.ts:427:37)
    at _Theatre._renderTheatre (Theatre.js:1994:29)
    at _Theatre.handleWindowResize (Theatre.js:5518:59)
    at _Theatre.configTheatreStyle (Theatre.js:447:14)
    at _Theatre._injectHTML (Theatre.js:181:14)
    at _Theatre.initialize (Theatre.js:108:14)
    at Object.fn (module.js:455:13)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at ChatLog._callHooks (foundry.js:5918:13)
    at ChatLog._render (foundry.js:5879:10)
    at async ChatLog._render (foundry.js:72780:5)
    at async ChatLog._render (foundry.js:89330:5)
    at async Promise.all (index 2)

**Comment by MrFlaig** [comment]
Yeah Sequencer fixed it just a minute ago....
